package com.ndobriukha.onlinemarketplace.dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.List;

import org.apache.commons.dbutils.BasicRowProcessor;
import org.apache.commons.dbutils.QueryRunner;
import org.apache.commons.dbutils.ResultSetHandler;
import org.apache.commons.dbutils.RowProcessor;
import org.apache.commons.dbutils.handlers.BeanHandler;
import org.apache.commons.dbutils.handlers.BeanListHandler;

import com.ndobriukha.onlinemarketplace.dbutils.MyQueryRunner;
import com.ndobriukha.onlinemarketplace.models.RetrieveFieldsValues;

public abstract class AbstractJdbcDao<T extends Identified<PK>, PK extends Integer>
		implements GenericDao<T, PK> {

	protected Connection connection;

	private Class<T> type;

	private RowProcessor convert;

	public AbstractJdbcDao(Connection connection, Class<T> type) {
		this(connection, type, new BasicRowProcessor());
	}

	public AbstractJdbcDao(Connection connection, Class<T> type,
			RowProcessor convert) {
		this.connection = connection;
		this.type = type;
		this.convert = convert;
	}

	public abstract String[] getAutoGeneratedKeys();

	public abstract String getSelectQuery();

	public abstract String getCreateQuery();

	public abstract String getUpdateQuery();

	public abstract String getDeleteQuery();

	@Override
	public T persist(T object) throws PersistException {
		if (object.getId() != null) {
			throw new PersistException("Object is already persist.");
		}
		T persistInstance;
		String sql = getCreateQuery();
		MyQueryRunner query = new MyQueryRunner(true);
		ResultSetHandler<T> resultHandler = new BeanHandler<T>(
				(Class<T>) object.getClass(), convert);
		String[] columnNames = getAutoGeneratedKeys();
		Object[] columnValues = ((RetrieveFieldsValues) object)
				.getFieldsValues();
		try {
			persistInstance = (T) query.insert(connection, sql, columnNames,
					resultHandler, columnValues);
		} catch (SQLException e) {
			if (e.getErrorCode() == 1) {
				throw new PersistConstraintException(e);
			} else {
				throw new PersistException(e);
			}
		}
		return persistInstance;
	}

	public T getByPK(Integer key) throws PersistException {
		List<T> list = null;
		String sql = getSelectQuery() + " WHERE id = ?";
		BeanListHandler<T> beanListHandler = new BeanListHandler<T>(type,
				convert);
		QueryRunner query = new QueryRunner();
		try {
			list = query.query(connection, sql, beanListHandler, key);
		} catch (SQLException e) {
			throw new PersistException(e);
		}
		if (list == null || list.size() == 0) {
			return null;
		}
		if (list.size() > 1) {
			throw new PersistException("Received more than one record.");
		}
		return list.get(0);
	}

	@Override
	public void update(T object) throws PersistException {
		String sql = getUpdateQuery();
		QueryRunner query = new QueryRunner();
		try {
			Object[] params = ((RetrieveFieldsValues) object).getFieldsValues();
			params = Arrays.copyOf(params, params.length + 1);
			params[params.length - 1] = object.getId().toString();
			int count = query.update(connection, sql, params);
			if (count != 1) {
				throw new PersistException(
						"On update modify more then 1 record: " + count);
			}
		} catch (SQLException e) {
			throw new PersistException(e);
		}
	}

	@Override
	public void delete(T object) throws PersistException {
		String sql = getDeleteQuery();
		try (PreparedStatement statement = connection.prepareStatement(sql)) {
			try {
				statement.setObject(1, object.getId());
			} catch (Exception e) {
				throw new PersistException(e);
			}
			int count = statement.executeUpdate();
			if (count != 1) {
				throw new PersistException(
						"On delete modify more then 1 record: " + count);
			}
			statement.close();
		} catch (Exception e) {
			throw new PersistException(e);
		}
	}

	@Override
	public List<T> getAll() throws PersistException {
		List<T> list = null;
		String sql = getSelectQuery();
		BeanListHandler<T> beanListHandler = new BeanListHandler<T>(type,
				convert);
		QueryRunner query = new QueryRunner();
		try {
			list = query.query(connection, sql, beanListHandler);
		} catch (SQLException e) {
			throw new PersistException(e);
		}
		return list;
	}
}
