package com.ndobriukha.onlinemarketplace.dao.oracle;

import java.sql.Connection;
import java.util.Date;

import com.ndobriukha.onlinemarketplace.dao.AbstractJdbcDao;
import com.ndobriukha.onlinemarketplace.dao.PersistException;
import com.ndobriukha.onlinemarketplace.dbutils.ItemRowProcessor;
import com.ndobriukha.onlinemarketplace.models.Item;

public class OracleItemDao extends AbstractJdbcDao<Item, Integer> {

	public OracleItemDao(Connection connection) {
		super(connection);
	}

	@Override
	public String[] getAutoGeneratedKeys() {
		return new String[] { "id", "sellerId", "description", "startPrice",
				"timeLeft", "startBidding", "buyItNow", "bidIncrement" };
	}

	@Override
	public String getSelectQuery() {
		return "SELECT id, sellerId, description, startPrice, timeLeft, startBidding, "
				+ "buyItNow, bidIncrement FROM Items";
	}

	@Override
	public String getCreateQuery() {
		/*return "INSERT INTO Items "
				+ "(sellerId, description, startPrice, timeLeft, "
				+ "startBidding, buyItNow, bidIncrement) "
				+ "VALUES(?, ?, ?, ?, ?, ?, ?) FROM Items";*/
		return "INSERT INTO Items "
		+ "(sellerId, description, startPrice, timeLeft, buyItNow) VALUES(?, ?, ?, ?, ?)";
	}

	@Override
	public String getUpdateQuery() {
		return "UPDATE Items SET "
				+ "sellerId = ?, description = ?, startPrice = ?, "
				+ "timeLeft = ?, startBidding = ?, buyItNow = ?, bidIncrement = ? "
				+ "WHERE id = ?";
	}

	@Override
	public String getDeleteQuery() {
		return "DELETE FROM Items WHERE id = ?";
	}

	public Item create(int sellerId, String description, double startPrice,
			int timeLeft, Date startBidding, Item.BuyItNowType buyItNow,
			double bidIncrement) throws PersistException {
		Item item = new Item(sellerId, description, startPrice, timeLeft,
				startBidding, buyItNow, bidIncrement);
		return persist(item, new ItemRowProcessor());
	}

}
