--------------------------------------------------------
--  File created - Friday-April-24-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BIDS
--------------------------------------------------------

  CREATE TABLE "MARKETPLACE"."BIDS" 
   (	"BID_ID" NUMBER(10,0), 
	"BIDDER_ID" NUMBER(10,0), 
	"ITEM_ID" NUMBER(10,0), 
	"BID" NUMBER(*,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BIDS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MARKETPLACE"."BIDS_PK" ON "MARKETPLACE"."BIDS" ("BID_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BIDS_ITEM
--------------------------------------------------------

  CREATE INDEX "MARKETPLACE"."BIDS_ITEM" ON "MARKETPLACE"."BIDS" ("BIDDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BIDS
--------------------------------------------------------

  ALTER TABLE "MARKETPLACE"."BIDS" ADD CONSTRAINT "BIDS_PK" PRIMARY KEY ("BID_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MARKETPLACE"."BIDS" MODIFY ("ITEM_ID" NOT NULL ENABLE);
  ALTER TABLE "MARKETPLACE"."BIDS" MODIFY ("BIDDER_ID" NOT NULL ENABLE);
  ALTER TABLE "MARKETPLACE"."BIDS" MODIFY ("BID_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BIDS
--------------------------------------------------------

  ALTER TABLE "MARKETPLACE"."BIDS" ADD CONSTRAINT "BIDS_FK1" FOREIGN KEY ("BID_ID")
	  REFERENCES "MARKETPLACE"."USERS" ("USER_ID") ENABLE;
  ALTER TABLE "MARKETPLACE"."BIDS" ADD CONSTRAINT "BIDS_FK2" FOREIGN KEY ("ITEM_ID")
	  REFERENCES "MARKETPLACE"."ITEMS" ("ITEM_ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger BIDS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MARKETPLACE"."BIDS_TRG" 
BEFORE INSERT ON BIDS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.BID_ID IS NULL THEN
      SELECT BIDS_KEY.NEXTVAL INTO :NEW.BID_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "MARKETPLACE"."BIDS_TRG" ENABLE;
