--------------------------------------------------------
--  File created - Friday-April-24-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ITEMS
--------------------------------------------------------

  CREATE TABLE "MARKETPLACE"."ITEMS" 
   (	"ITEM_ID" NUMBER(10,0), 
	"SELLER_ID" NUMBER(10,0), 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"START_PRICE" NUMBER(*,2), 
	"TIME_LEFT" NUMBER(*,0), 
	"START_BIDDING_TS" TIMESTAMP (6), 
	"BUY_IT_NOW" CHAR(1 CHAR), 
	"BID_ICREMENT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ITEMS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MARKETPLACE"."ITEMS_PK" ON "MARKETPLACE"."ITEMS" ("ITEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ITEMS
--------------------------------------------------------

  ALTER TABLE "MARKETPLACE"."ITEMS" ADD CONSTRAINT "ITEMS_CHK" CHECK (BUY_IT_NOW in ('N','Y')) ENABLE;
  ALTER TABLE "MARKETPLACE"."ITEMS" ADD CONSTRAINT "ITEMS_PK" PRIMARY KEY ("ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MARKETPLACE"."ITEMS" MODIFY ("BUY_IT_NOW" NOT NULL ENABLE);
  ALTER TABLE "MARKETPLACE"."ITEMS" MODIFY ("START_BIDDING_TS" NOT NULL ENABLE);
  ALTER TABLE "MARKETPLACE"."ITEMS" MODIFY ("TIME_LEFT" NOT NULL ENABLE);
  ALTER TABLE "MARKETPLACE"."ITEMS" MODIFY ("START_PRICE" NOT NULL ENABLE);
  ALTER TABLE "MARKETPLACE"."ITEMS" MODIFY ("SELLER_ID" NOT NULL ENABLE);
  ALTER TABLE "MARKETPLACE"."ITEMS" MODIFY ("ITEM_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ITEMS
--------------------------------------------------------

  ALTER TABLE "MARKETPLACE"."ITEMS" ADD CONSTRAINT "ITEMS_FK" FOREIGN KEY ("SELLER_ID")
	  REFERENCES "MARKETPLACE"."USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger ITEMS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MARKETPLACE"."ITEMS_TRG" 
BEFORE INSERT ON ITEMS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ITEM_ID IS NULL THEN
      SELECT ITEMS_KEY.NEXTVAL INTO :NEW.ITEM_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "MARKETPLACE"."ITEMS_TRG" ENABLE;
